name: 'Build your docs with DocsAsCode'
description: 'Action to create professionnal documents(PDF) from md, rst or adoc. Based on docsAsCode project.'
author: 'docsascode <docsascode@protonmail.com>'
inputs:
  sources:
    description: 'List of glob patterns to your source files'
    required: true
    default: '.'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.sources }}
 
branding:
  icon: 'book'
  color: 'red'
