on:
  push:
    paths: 
      - 'Example/*.md'
jobs:
  md2pdf:
    runs-on: ubuntu-latest
    name: A job to test this action
    env:
      DEFAULT_DESTINATION: 'Example/build/'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        uses: ./
        with:
          sources: 'Example/*.md'
          default_outputs: 'output.slides'
      - name: Publish
        uses: actions/upload-artifact@v2
        with:
          path: ${env.DEFAULT_DESTINATION}/*.pdf
